# parsers/base/constants.py — lookup tables shared across the base modules.
# Extracted from base.py.

# ══════════════════════════════════════════════════════════════════════════════
#  BRAND NORMALIZATION
# ══════════════════════════════════════════════════════════════════════════════

KNOWN_BRANDS = {
    "audi", "bmw", "mercedes", "mercedes-benz", "volkswagen", "vw",
    "volvo", "toyota", "honda", "mazda", "skoda", "seat", "cupra",
    "ford", "opel", "peugeot", "renault", "citroen", "hyundai", "kia",
    "nissan", "mitsubishi", "subaru", "lexus", "porsche", "tesla",
    "mini", "jeep", "land rover", "landrover", "jaguar", "alfa romeo",
    "alfa", "saab", "suzuki", "dacia", "fiat", "chrysler", "dodge",
    "chevrolet", "cadillac", "genesis",
}

MAKE_NORMALIZE = {
    "BMW": "BMW", "VW": "Volkswagen", "VOLKSWAGEN": "Volkswagen",
    "MERCEDES": "Mercedes-Benz", "MERCEDES-BENZ": "Mercedes-Benz",
    "LAND ROVER": "Land Rover", "LANDROVER": "Land Rover",
    "ALFA": "Alfa Romeo", "ALFA ROMEO": "Alfa Romeo",
    "MINI": "MINI", "SAAB": "Saab", "KIA": "Kia",
    "AUDI": "Audi", "VOLVO": "Volvo", "TOYOTA": "Toyota",
    "HONDA": "Honda", "MAZDA": "Mazda", "SKODA": "Skoda",
    "SEAT": "SEAT", "CUPRA": "Cupra",
    "FORD": "Ford", "OPEL": "Opel", "PEUGEOT": "Peugeot",
    "RENAULT": "Renault", "CITROEN": "Citroen",
    "HYUNDAI": "Hyundai", "NISSAN": "Nissan",
    "MITSUBISHI": "Mitsubishi", "SUBARU": "Subaru",
    "LEXUS": "Lexus", "PORSCHE": "Porsche", "TESLA": "Tesla",
    "JEEP": "Jeep", "JAGUAR": "Jaguar",
    "SUZUKI": "Suzuki", "DACIA": "Dacia", "FIAT": "Fiat",
    "CHRYSLER": "Chrysler", "DODGE": "Dodge",
    "CHEVROLET": "Chevrolet", "CADILLAC": "Cadillac",
    "GENESIS": "Genesis",
}

FUEL_NORMALIZE = {
    "petrol": "Petrol", "gasoline": "Petrol", "benzin": "Petrol",
    "bensin": "Petrol", "diesel": "Diesel",
    "electric": "Electric", "elektro": "Electric", "elektrisk": "Electric",
    "elbil": "Electric", "el": "Electric",
    "hybrid": "Hybrid", "laddhybrid": "Hybrid",
    "hybrid_petrol": "Hybrid", "hybrid_diesel": "Hybrid",
    "lpg": "LPG", "cng": "CNG",
}

FUEL_UA = {
    "Petrol": "Бензин", "Diesel": "Дизель",
    "Electric": "Електро", "Hybrid": "Гібрид",
    "LPG": "Газ", "CNG": "Газ",
}

COLOR_EN = {
    "black": "Black", "white": "White", "silver": "Silver",
    "grey": "Grey", "gray": "Grey", "blue": "Blue",
    "red": "Red", "green": "Green", "brown": "Brown",
    "beige": "Beige", "orange": "Orange", "yellow": "Yellow",
    "gold": "Gold", "purple": "Purple", "bronze": "Bronze",
    # Swedish (with special chars)
    "svart": "Black", "vit": "White",
    "grå": "Grey", "gra": "Grey",
    "blå": "Blue", "bla": "Blue",
    "röd": "Red", "rod": "Red",
    "grön": "Green", "gron": "Green",
    "brun": "Brown", "gul": "Yellow", "guld": "Gold", "lila": "Purple",
    # German
    "schwarz": "Black", "weiss": "White", "weiß": "White",
    "silber": "Silver", "grau": "Grey", "blau": "Blue",
    "rot": "Red", "grün": "Green", "braun": "Brown", "gelb": "Yellow",
}

COLOR_UA = {
    "Black": "Чорний", "White": "Білий", "Silver": "Сріблястий",
    "Grey": "Сірий", "Blue": "Синій", "Red": "Червоний",
    "Green": "Зелений", "Brown": "Коричневий", "Beige": "Бежевий",
    "Orange": "Помаранчевий", "Yellow": "Жовтий", "Gold": "Золотий",
    "Purple": "Фіолетовий", "Bronze": "Бронзовий",
}

BODY_EN = {
    "sedan": "Sedan", "saloon": "Sedan", "limousine": "Sedan",
    "estate": "Estate", "station wagon": "Estate", "wagon": "Estate",
    "suv": "SUV", "crossover": "SUV", "offroad": "SUV",
    "hatchback": "Hatchback",
    "coupe": "Coupe", "convertible": "Convertible", "cabriolet": "Convertible",
    "van": "Van", "minivan": "Van", "mpv": "Van",
    "pickup": "Pickup",
    "kombi": "Estate", "halvkombi": "Hatchback",
    "cab": "Convertible", "minibuss": "Van",
}

BODY_UA = {
    "Sedan": "Седан", "Estate": "Універсал", "SUV": "Позашляховик",
    "Hatchback": "Хетчбек", "Coupe": "Купе", "Convertible": "Кабріолет",
    "Van": "Мінівен", "Pickup": "Пікап",
}

DRIVE_NORMALIZE = {
    "front wheel drive": "FWD", "fwd": "FWD", "framhjulsdrift": "FWD",
    "front_wheel": "FWD", "frontwheel": "FWD",
    "rear wheel drive": "RWD", "rwd": "RWD", "bakhjulsdrift": "RWD",
    "rear_wheel": "RWD", "rearwheel": "RWD",
    "all wheel drive": "AWD", "awd": "AWD", "4wd": "AWD",
    "all_wheel": "AWD", "allwheel": "AWD",
    "fyrhjulsdrift": "AWD", "4-motion": "AWD", "quattro": "AWD", "xdrive": "AWD",
}

TRANS_NORMALIZE = {
    "automatic": "Automatic", "auto": "Automatic", "automatik": "Automatic",
    "automat": "Automatic", "dsg": "Automatic", "tiptronic": "Automatic",
    "s tronic": "Automatic", "pdk": "Automatic", "cvt": "Automatic",
    "manual": "Manual", "manuell": "Manual", "schaltgetriebe": "Manual",
}


# ══════════════════════════════════════════════════════════════════════════════
#  SWEDISH FEATURE TRANSLATION
# ══════════════════════════════════════════════════════════════════════════════

SV_FEATURES: dict[str, tuple[str, str]] = {
    # Safety
    "abs-bromsar": ("ABS", "safety"),
    "airbag förare": ("Driver airbag", "safety"),
    "airbag passagerare fram": ("Passenger airbag", "safety"),
    "avstängningsbar airbag passagerare": ("Deactivatable passenger airbag", "safety"),
    "sidoairbags": ("Side airbags", "safety"),
    "sidokrockgardiner": ("Side curtain airbags", "safety"),
    "antisladd": ("Electronic stability control", "safety"),
    "autobroms": ("Automatic emergency braking", "safety"),
    "broms-assistans": ("Brake assist", "safety"),
    "backstartshjälp": ("Hill start assist", "safety"),
    "körfilsassistans": ("Lane keeping assist", "safety"),
    "laneassist": ("Lane assist", "safety"),
    "trötthetsvarnare": ("Driver drowsiness detection", "safety"),
    "startspärr": ("Immobilizer", "safety"),
    "stöldlarm": ("Alarm system", "safety"),
    "barnlås": ("Child lock", "safety"),
    "isofix-fästen bak": ("ISOFIX rear", "safety"),
    "isofix-fästen fram": ("ISOFIX front", "safety"),
    "ljussensor": ("Light sensor", "safety"),
    "regnsensor": ("Rain sensor", "safety"),
    "parkeringssensorer": ("Parking sensors", "safety"),
    "backkamera": ("Rear camera", "safety"),
    "dimljus fram": ("Front fog lights", "safety"),
    "led strålkastare": ("LED headlights", "safety"),
    "led (halvljus)": ("LED low beam", "safety"),
    "bi-xenonstrålkastare": ("Bi-xenon headlights", "safety"),
    "xenon (helljus)": ("Xenon high beam", "safety"),
    "fotgängardetektion": ("Pedestrian detection", "safety"),
    "nödsamtal": ("Emergency call system", "safety"),
    "euro ncap 5": ("Euro NCAP 5 stars", "safety"),
    "euro 6": ("Euro 6 emissions", "safety"),
    "fartbegränsare": ("Speed limiter", "safety"),
    # Comfort
    "farthållare": ("Cruise control", "comfort"),
    "farthållare (adaptiv)": ("Adaptive cruise control", "comfort"),
    "adaptiv farthållare": ("Adaptive cruise control", "comfort"),
    "acc": ("Adaptive cruise control", "comfort"),
    "sätesvärme (fram)": ("Front seat heating", "comfort"),
    "rattvärme": ("Heated steering wheel", "comfort"),
    "delbart baksäte": ("Split rear seat", "comfort"),
    "fällbara baksäten": ("Folding rear seats", "comfort"),
    "elhissar (fram och bak)": ("Electric windows front+rear", "comfort"),
    "elhissar (fram)": ("Electric windows front", "comfort"),
    "elinfällbara sidospeglar": ("Electrically folding mirrors", "comfort"),
    "eluppvärmda sidospeglar": ("Heated side mirrors", "comfort"),
    "centrallås (fjärrstyrt)": ("Remote central locking", "comfort"),
    "keyless nyckelfri start": ("Keyless entry + start", "comfort"),
    "multifunktionsratt": ("Multi-function steering wheel", "comfort"),
    "sportratt": ("Sport steering wheel", "comfort"),
    "sportstolar": ("Sport seats", "comfort"),
    "luftkonditionering": ("Air conditioning", "comfort"),
    "acc 2 klimatzoner": ("Dual-zone climate control", "comfort"),
    "dragkrok": ("Tow bar", "comfort"),
    "dragkrok (utfällbar)": ("Retractable tow bar", "comfort"),
    "elbaklucka": ("Electric tailgate", "comfort"),
    "tonade rutor": ("Tinted windows", "comfort"),
    "rails": ("Roof rails", "comfort"),
    "servostyrning": ("Power steering", "comfort"),
    "start-/stoppfunktion": ("Start-stop system", "comfort"),
    "motorvärmare (fjärrstyrd)": ("Remote engine heater", "comfort"),
    "motorvärmare (med tidur)": ("Engine heater with timer", "comfort"),
    "bränslevärmare": ("Fuel heater", "comfort"),
    "uppvärmda spolare": ("Heated washer nozzles", "comfort"),
    "kylt handskfack": ("Cooled glove compartment", "comfort"),
    "plant lastutrymme": ("Flat cargo area", "comfort"),
    "avbländande innerbackspegel": ("Auto-dimming rear mirror", "comfort"),
    "läslampa": ("Reading light", "comfort"),
    "sminkspegel": ("Vanity mirror", "comfort"),
    # Infotainment
    "bluetooth (handsfree)": ("Bluetooth handsfree", "infotainment"),
    "android auto": ("Android Auto", "infotainment"),
    "apple carplay": ("Apple CarPlay", "infotainment"),
    "usb-uttag": ("USB port", "infotainment"),
    "aux-ingång": ("AUX input", "infotainment"),
    "cd-stereo": ("CD player", "infotainment"),
    "digitalradio (dab)": ("Digital radio DAB", "infotainment"),
    "gps": ("Navigation system", "infotainment"),
    "färddator": ("On-board computer", "infotainment"),
    "touch-/pekskärm": ("Touch screen", "infotainment"),
    "digitalt mätarhus": ("Digital cockpit", "infotainment"),
    "akustikrutor": ("Acoustic glass", "infotainment"),
    "trådlös telefonladdare": ("Wireless phone charging", "infotainment"),
    # Comfort (additional)
    "panoramatak": ("Panoramic roof", "comfort"),
    "panoramatakvindor": ("Panoramic sunroof", "comfort"),
    "panoramaglastak": ("Panoramic glass roof", "comfort"),
    "soltak": ("Sunroof", "comfort"),
    "taklucka": ("Sunroof", "comfort"),
    "motorvärmare": ("Engine heater", "comfort"),
    "webasto": ("Webasto heater", "comfort"),
    "kupévärmare": ("Cabin heater", "comfort"),
    "el-stolar": ("Electric seats", "comfort"),
    "elsäte förare": ("Electric driver seat", "comfort"),
    "elsäte passagerare": ("Electric passenger seat", "comfort"),
    "minnesfunktion säte": ("Seat memory function", "comfort"),
    "skinnklädsel": ("Leather upholstery", "comfort"),
    "skinninredning": ("Leather interior", "comfort"),
    "alcantara": ("Alcantara upholstery", "comfort"),
    "ryggmassage": ("Seat massage", "comfort"),
    "armstöd": ("Armrest", "comfort"),
    "lastgaller": ("Cargo net", "comfort"),
    "lastnät": ("Cargo net", "comfort"),
    "parkeringshjälp": ("Parking assist", "comfort"),
    "automatisk parkering": ("Automatic parking", "comfort"),
    "luftfjädring": ("Air suspension", "comfort"),
    "adaptiv fjädring": ("Adaptive suspension", "comfort"),
    "head-up display": ("Head-up display", "comfort"),
    "head up display": ("Head-up display", "comfort"),
    "ambitionsbelysning": ("Ambient lighting", "comfort"),
    "ambient belysning": ("Ambient lighting", "comfort"),
    "induktionsladdning": ("Wireless charging", "comfort"),
    "eluppvärmd vindruta": ("Heated windshield", "comfort"),
    "uppvärmd vindruta": ("Heated windshield", "comfort"),
    # Safety (additional)
    "360-kamera": ("360-degree camera", "safety"),
    "360 graders kamera": ("360-degree camera", "safety"),
    "dödvinkelassistans": ("Blind spot assist", "safety"),
    "dödvinkelvarning": ("Blind spot warning", "safety"),
    "avståndsvarnare": ("Distance warning", "safety"),
    "skyltavläsare": ("Speed sign recognition", "safety"),
    "trafikskyltavläsning": ("Traffic sign recognition", "safety"),
    "nattseende": ("Night vision", "safety"),
    "adaptiva strålkastare": ("Adaptive headlights", "safety"),
    "adaptiv kurvljus": ("Adaptive cornering lights", "safety"),
    "helljusassistans": ("High beam assist", "safety"),
    "dragkontroll": ("Traction control", "safety"),
    "dimmljus bak": ("Rear fog lights", "safety"),
    "matrixljus": ("Matrix LED headlights", "safety"),
    "laserljus": ("Laser headlights", "safety"),
    # Infotainment (additional)
    "soundsystem": ("Premium sound system", "infotainment"),
    "harman kardon": ("Harman Kardon sound", "infotainment"),
    "bose": ("Bose sound system", "infotainment"),
    "bang & olufsen": ("Bang & Olufsen sound", "infotainment"),
    "b&o": ("Bang & Olufsen sound", "infotainment"),
    "burmester": ("Burmester sound system", "infotainment"),
    "wifi": ("WiFi hotspot", "infotainment"),
    "wlan": ("WiFi hotspot", "infotainment"),
    "navigationssystem": ("Navigation system", "infotainment"),
    "fjärrstrålkastare": ("High beam headlights", "safety"),
    "digital tv": ("Digital TV", "infotainment"),
    # Other
    "svensksåld": ("Sold new in Sweden", "other"),
    "yttertemperaturmätare": ("Outside temperature display", "other"),
    "7-sits": ("7 seats", "other"),
    "5-sits": ("5 seats", "other"),
    "s-line": ("S-Line package", "other"),
    "svart optik": ("Black optics package", "other"),
    "m-sport": ("M-Sport package", "other"),
    "amg": ("AMG package", "other"),
    "r-design": ("R-Design package", "other"),
    "inscription": ("Inscription package", "other"),
    "momentum": ("Momentum package", "other"),
    "sportline": ("Sportline package", "other"),
    "vinterhjul": ("Winter wheels", "other"),
    "sommarhjul": ("Summer wheels", "other"),
    "reservhjul": ("Spare wheel", "other"),
    "lättmetallfälgar": ("Alloy wheels", "other"),
    "aluminiumfälgar": ("Aluminum wheels", "other"),
    "autohold": ("Auto hold", "comfort"),
    "fjärrstyrd motorvärmare": ("Remote engine preheater", "comfort"),
}


